### ISSUE TITLE
run on raspberry got signal and noise always 0

### ISSUE THREAD

**Issue by ixqbar** [ayourtch/beacondump#1]
-483146300 len 333   freq   11 rate 88500 s/n: 0 0 seq 96a BSS 2c3ecfb725e2 | .
-483116377 len 343   freq   15 rate 72500 s/n: 0 0 seq 96b BSS 2c3ecfb725e1 | Quark-Guest
-483106378 len 288   freq   15 rate 107500 s/n: 0 0 seq a85 BSS 64d954066340 | ............ 
-483066407 len 286   freq   12 rate 116500 s/n: 0 0 seq 96d BSS 2c3ecfb725e0 | Quark-WIFI
-483036394 len 333   freq   13 rate 100500 s/n: 0 0 seq 96e BSS 2c3ecfb725e2 | .

**Comment by ayourtch** [comment]
Seems like a lot of things are wrong besides that - the time, rate and frequency... I don't have RPI though...

**Comment by ixqbar** [comment]
give me your mail, i send you my rpi machine ssh info, can help?

**Comment by ayourtch** [comment]
Did you get it running ? Sorry a bit busy these days, so might not be able to look at this until +1month or so. Which RPi model did you use though ? Did it have built-in wifi ? I might get one for myself eventually and will keep this in mind...

**Comment by ixqbar** [comment]
thanks, I don't confirm whether my wifi driver has a problem, i changed other wifi it works well!
